[project]
name = "relay-order-form"
version = "0.1.0"
description = "All Japan orienteering relay competition start order form"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "st-gsheets-connection>=0.1.0",
    "streamlit>=1.50.0",
]
